spring.application.name=harsh-artz-backend

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://ankit161210_db_user:OWHJirMRy0L5oq02@cluster0.dnhhh2c.mongodb.net/harsh_artz?retryWrites=true&w=majority
spring.data.mongodb.database=Harsh_artz

# Server
server.port=8081

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB